basePath: /
definitions:
  handler.closeData:
    properties:
      dealid:
        type: string
    required:
    - dealid
    type: object
  handler.dealData:
    properties:
      company:
        type: string
      sharescount:
        type: number
      stoploss:
        type: number
      takeprofit:
        type: number
    required:
    - company
    - sharescount
    - stoploss
    - takeprofit
    type: object
  handler.inputData:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  model.Balance:
    properties:
      operation:
        description: sum of money to be deposit or withdraw
        type: number
    required:
    - operation
    type: object
  model.Deal:
    properties:
      company:
        description: name of company in share
        type: string
      dealid:
        description: id of deal - each deal have new id
        type: string
      dealtime:
        description: entry time in position
        type: string
      purchaseprice:
        description: entry price in position
        type: number
      sharescount:
        description: amount of shares of the selected transaction company
        type: number
      stoploss:
        description: lower limit where the price can go
        type: number
      takeprofit:
        description: upper limit where the price can go
        type: number
    required:
    - company
    - stoploss
    - takeprofit
    type: object
  model.Share:
    properties:
      company:
        type: string
      price:
        type: number
    type: object
  model.TokenPair:
    properties:
      accesstoken:
        description: token that gives access to secure methods
        type: string
      refreshtoken:
        description: same token as in struct User
        type: string
    type: object
host: localhost:7777
info:
  contact: {}
  description: Trading System with 2 strategies (Long and Short).
  title: Trade API
  version: "1.0"
paths:
  /closeposition:
    post:
      consumes:
      - application/json
      operationId: close-position
      parameters:
      - description: Please fill the id of deal
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.closeData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Close the position
      tags:
      - auth
  /delete:
    delete:
      consumes:
      - application/json
      operationId: delete-account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete your account
      tags:
      - auth
  /deposit:
    post:
      consumes:
      - application/json
      operationId: deposit
      parameters:
      - description: Please input the amount of money to deposit
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Balance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Balance operation deposit
      tags:
      - auth
  /getbalance:
    get:
      consumes:
      - application/json
      operationId: get-operation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Check sum of money on your balance
      tags:
      - auth
  /getprices:
    get:
      consumes:
      - application/json
      operationId: get-prices
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Share'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Show prices of shares
      tags:
      - auth
  /getunclosed:
    get:
      consumes:
      - application/json
      operationId: get-unclosed
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Deal'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Show all unclosed positions
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: Please fill the login and password fields.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.inputData'
      produces:
      - application/json
      responses:
        "200":
          description: tokens
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Account login
      tags:
      - auth
  /long:
    post:
      consumes:
      - application/json
      operationId: long
      parameters:
      - description: Please fill the SraresCount,Company,StopLoss and TakeProfit fields.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.dealData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Invest money with strategy "long"
      tags:
      - auth
  /refresh:
    post:
      consumes:
      - application/json
      operationId: refresh-token
      parameters:
      - description: Please fill the access and refresh tokens fields.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.TokenPair'
      produces:
      - application/json
      responses:
        "200":
          description: tokens
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Refresh tokens
      tags:
      - auth
  /short:
    post:
      consumes:
      - application/json
      operationId: short
      parameters:
      - description: Please fill the fields about Share.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.dealData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Invest money with strategy "short"
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      operationId: create-account
      parameters:
      - description: Please fill the login (5-20 symbols) and password (minimum 8
          symbols) fields.
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.inputData'
      produces:
      - application/json
      responses:
        "201":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: Registration
      tags:
      - auth
  /withdraw:
    post:
      consumes:
      - application/json
      operationId: withdraw
      parameters:
      - description: Please input the amount of money to withdraw
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Balance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Balance operation withdraw
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
